# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-stereolabs"
BBFILE_PATTERN_meta-stereolabs = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-stereolabs = "30"

LAYERDEPENDS_meta-stereolabs = "core"
LAYERSERIES_COMPAT_meta-stereolabs = "scarthgap"
